---
title: "L01 Review"
subtitle: "Data Science 3 with R (STAT 301-3)"
author: "Steven Yang"
pagetitle: "L01 Steven Yang"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin   
---

::: {.callout-tip icon="false"}
## Github Repo Link

[GitHub Repo](https://github.com/stat301-3-2026-spring/l01-review-stevenyang406)
:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

## Questions

When completing the following questions ensure your solutions are neatly formatted and clearly indicated. Consider including diagrams/images in some of your solutions, if it helps to make things easier to describe/discuss.

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution

- Defining Problem
- EDA
- Data Splitting
- Feature Engineering
- Data Preprocessing
- Hyperparameter Tuning
- Model Analysis/Selection
- Final Model Training
- Model Evaluation

:::

### Question 2

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution

Supervised learning tends to have a set question in mind. For regression problems, it may be predicting the price of a home. For classification problems, it may be predicting whether a person on the Titanic survived. Unsupervised learning does not have a set problem in mind and instead tries to find patterns or structure within a set of unlabeled data.

:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution

Descriptive models tend to focus on summarizing characteristics of historical data visually. One example could be showing a graph of changing average temperatures globally over time.

:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution

Inferential models involve hypothesis testing and test whether certain variables have statistically significant effects on a given outcome variable.

:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution

Predictive models use past data to forecast a future observation's outcome variables based on a set of explanatory variables. For instance, one predictive model could be used to estimate a house's sale price based on the square footage and number of rooms.
:::

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution

A mechanistic model assumes that the distribution of the outcome variable can be explained by some theory of how other variables change.

:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution

Empirically driven models like random forest use the data itself to predict the outcome variable with no assumptions about the form of the outcome variable's distribution.

:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution

Mechanistic models tend to be parametric because parametric models are those that follow a certain equation or functinoal form. Nonparametric models have no assumptions about the data and can find more complex relationships from studying the data exclusively, which makes it empirically driven.

:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution

Mechanistic models are easier to interpret because changes in one variable can be directly linked to a change in the outcome variable, while empirically driven models can be far more complicated.

:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution

Empirically driven models are more flexible since they are not bound to a specific equation or known form.

:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution

Generally, mechanistic models tend to have higher bias and lower variance since you are essentially fixed to how biased the equation or form you are using is. Empirically driven models that are more flexible generally have low bias since they can more accurately find more complicated relationships, but variance can be high if the model is fitting to noise in the data.

:::

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution

Classification problems provide prediction for categorical variables (such as whether someone on the Titanic will survive or not) while regression problems provide predictions for continuous numeric variables like house prices.

:::

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution

It is important that the smaller sets of data you have are generally representative of the full data. This reduces the risk that your models will be off because the distribution of the outcome variable is substantially different in different splits. This is especially important when there is a class imbalance.

:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

V-fold cross validation randomly splits the training data into v folds. Each of the folds is used as the assessment set once while the other v-1 folds are used to train the model. The RMSE is calculated, then the process is repeated using a different fold as the assessment set. After all folds have been used as the assessment set once, the training data is split into v folds again until the number of repeats is reached. All of these RMSEs are then averaged to give an estimate of test RMSE.

:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

One scenario where a bootstrap resampling procedure would be more appropriate would be when you have limited data because bootstrap resampling allows you to make better estimates of RMSE with less variance compared to v-fold cross validation estimates.

:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution

We use model tuning because many model types have hyperparameters to set. In order to get the best possible performance, tuning is necessary to find which hyperparameters have the best metrics.

:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution

RMSE and MAE.

:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

Accuracy and ROC-AUC.

:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with a them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

This is an inferential problem because we are testing the hypothesis that higher service calls is important to determining churn likelihood.

:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

This is a prediction problem because we are using data to predict how likely a specific customer is to churn based on other explanatory variables we have available.

:::

